-- MySQL Script generated by MySQL Workbench
-- Fri May 12 22:38:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nycaccessibility
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nycaccessibility
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nycaccessibility` DEFAULT CHARACTER SET utf8 ;
USE `nycaccessibility` ;

-- -----------------------------------------------------
-- Table `nycaccessibility`.`oos_reason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`oos_reason` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reason_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `reason_name_UNIQUE` (`reason_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`equipment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`equipment_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`station_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`station_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`stations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NOT NULL,
  `ada_compliant` TINYINT NOT NULL,
  `station_type_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_stations_station_type1_idx` (`station_type_id` ASC),
  CONSTRAINT `fk_stations_station_type1`
    FOREIGN KEY (`station_type_id`)
    REFERENCES `nycaccessibility`.`station_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`equipment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `mta_id` CHAR(5) NOT NULL,
  `location` VARCHAR(225) NOT NULL,
  `type_id` INT NOT NULL,
  `stations_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_equipment_equipment_type_idx` (`type_id` ASC),
  INDEX `fk_equipment_stations1_idx` (`stations_id` ASC),
  CONSTRAINT `fk_equipment_equipment_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `nycaccessibility`.`equipment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_stations1`
    FOREIGN KEY (`stations_id`)
    REFERENCES `nycaccessibility`.`stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`elevator_escalator_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`elevator_escalator_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `oos_start` DATETIME NOT NULL,
  `oos_reason_id` INT NOT NULL,
  `equipment_id` BIGINT NOT NULL,
  `oos_end_estimate` DATETIME NOT NULL,
  `oos_end_actual` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_elevator_escalator_log_oos_reason1_idx` (`oos_reason_id` ASC),
  INDEX `fk_elevator_escalator_log_equipment1_idx` (`equipment_id` ASC),
  CONSTRAINT `fk_elevator_escalator_log_oos_reason1`
    FOREIGN KEY (`oos_reason_id`)
    REFERENCES `nycaccessibility`.`oos_reason` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elevator_escalator_log_equipment1`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `nycaccessibility`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`line_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`line_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`trainlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`trainlines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lines_name` VARCHAR(3) NOT NULL,
  `line_type_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`lines_name` ASC),
  INDEX `fk_lines_line_type1_idx` (`line_type_id` ASC),
  CONSTRAINT `fk_lines_line_type1`
    FOREIGN KEY (`line_type_id`)
    REFERENCES `nycaccessibility`.`line_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`stations_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`stations_lines` (
  `trainlines_id` INT NOT NULL,
  `stations_id1` BIGINT NOT NULL,
  INDEX `fk_stations_lines_trainlines1_idx` (`trainlines_id` ASC),
  INDEX `fk_stations_lines_stations1_idx` (`stations_id1` ASC),
  CONSTRAINT `fk_stations_lines_trainlines1`
    FOREIGN KEY (`trainlines_id`)
    REFERENCES `nycaccessibility`.`trainlines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stations_lines_stations1`
    FOREIGN KEY (`stations_id1`)
    REFERENCES `nycaccessibility`.`stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nycaccessibility`.`scrape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nycaccessibility`.`scrape` (
  `scrape_timestamp` DATETIME NOT NULL,
  `ada_compliant` TINYINT NOT NULL,
  `station_name` VARCHAR(45) NOT NULL,
  `train_lines_rawtext` VARCHAR(45) NOT NULL,
  `equipment_type_id` INT NOT NULL,
  `equipment_mta_id` CHAR(5) NOT NULL,
  `location_rawtext` VARCHAR(225) NOT NULL,
  `oos_start` DATETIME NOT NULL,
  `oos_reason_rawtext` VARCHAR(45) NOT NULL,
  `oos_end_estimate` DATETIME NOT NULL,
  `mta_last_update` DATETIME NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
