USE nycaccessibility;
INSERT INTO equipment_type VALUES (1, 'Elevator');
INSERT INTO equipment_type VALUES (2, 'Escalator');
INSERT INTO line_type VALUES (1, 'Subway');
INSERT INTO oos_reason VALUES (1, 'Repair');
INSERT INTO oos_reason VALUES (2, 'Replacement');
INSERT INTO oos_reason VALUES (3, 'Under Investigation');
INSERT INTO station_type VALUES (1, 'Subway');
INSERT INTO trainlines VALUES (1, 'A', 1);
INSERT INTO trainlines VALUES (2, 'C', 1);
INSERT INTO trainlines VALUES (3, 'E', 1);
INSERT INTO trainlines VALUES (4, 'B', 1);
INSERT INTO trainlines VALUES (5, 'D', 1);
INSERT INTO trainlines VALUES (6, 'F', 1);
INSERT INTO trainlines VALUES (7, 'M', 1);
INSERT INTO trainlines VALUES (8, 'G', 1);
INSERT INTO trainlines VALUES (9, 'L', 1);
INSERT INTO trainlines VALUES (10, 'J', 1);
INSERT INTO trainlines VALUES (11, 'Z', 1);
INSERT INTO trainlines VALUES (12, 'N', 1);
INSERT INTO trainlines VALUES (13, 'Q', 1);
INSERT INTO trainlines VALUES (14, 'R', 1);
INSERT INTO trainlines VALUES (15, 'W', 1);
INSERT INTO trainlines VALUES (16, '1', 1);
INSERT INTO trainlines VALUES (17, '2', 1);
INSERT INTO trainlines VALUES (18, '3', 1);
INSERT INTO trainlines VALUES (19, '4', 1);
INSERT INTO trainlines VALUES (20, '5', 1);
INSERT INTO trainlines VALUES (21, '6', 1);
INSERT INTO trainlines VALUES (22, '<6>', 1);
INSERT INTO trainlines VALUES (23, '7', 1);
INSERT INTO trainlines VALUES (24, '<7>', 1);
INSERT INTO trainlines VALUES (25, 'S', 1);